import React from 'react'

export const HomePage = () => {
  return (
    <div>
      <h1 className='text-2xl font-bold'>Welcome to Store-Xen POS</h1>
      <p className='text-gray-500 text-4xl'>This is the home page of Store-Xen POS Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, dolorem nulla error, suscipit quam doloremque et voluptates officia impedit non dignissimos sed aliquam praesentium illo dicta sapiente? Aliquid sint perspiciatis natus inventore hic nihil id, voluptatem quaerat libero. Corrupti ipsam maxime totam consectetur excepturi iure fuga corporis dicta quaerat veniam. Voluptates doloremque modi ad laborum unde ducimus veritatis accusantium, numquam, voluptatem autem odio et dolorum quo, sunt quidem quae debitis libero? Soluta deleniti sequi optio voluptatibus accusantium, voluptas exercitationem vitae incidunt cumque, fugiat mollitia pariatur! Neque ab praesentium ducimus ex, voluptates animi. Modi quo ratione culpa. Assumenda, odit esse, consequuntur eos explicabo, nam praesentium molestiae quisquam consequatur ea adipisci. Quisquam consectetur, cupiditate magnam, quo rem consequuntur voluptas dolor veritatis quibusdam quos dolore. Ea quisquam sed animi qui beatae molestiae consequatur! Ullam, placeat reprehenderit corrupti excepturi natus fugiat ipsum similique, ratione autem dicta accusantium consequuntur tempora suscipit quod amet nulla blanditiis repellendus? Debitis repellat, assumenda eligendi qui officiis voluptatem reprehenderit fugit, ea voluptate laboriosam ab dolore aliquid tenetur! Voluptates aut rerum dolorum eius? Odio quas ipsam ea quod quae rem excepturi nesciunt eaque aperiam sequi, inventore voluptatem eos itaque quis. Dicta a, nesciunt obcaecati ipsa dolorem magni dignissimos ea eius inventore libero voluptas minus recusandae saepe. Doloribus neque vel molestias sint repellat tempora repellendus in laboriosam ab dolores incidunt aliquam, ex, nihil, recusandae officiis perspiciatis obcaecati. Ipsum totam quos mollitia, illo delectus aliquam dolore aperiam, corporis numquam dicta vero reprehenderit quaerat doloremque architecto maxime? Voluptatibus sint maxime earum itaque. Totam voluptatum eaque fugit commodi modi, debitis natus rerum quo, nostrum voluptas eius, ipsa numquam ut labore iste. Quibusdam nobis dolores asperiores laboriosam ipsa eos cupiditate distinctio consectetur pariatur, suscipit doloremque cumque animi ipsam rem nam error est expedita labore repellat sint ut sequi eum amet accusantium. A delectus culpa beatae voluptas?</p>
    </div>
  )
}
